version: "3.8"

services:
  medibridge-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: medibridge-frontend
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - medibridge-network

networks:
  medibridge-network:
    driver: bridge
